/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package breakoutPanel;

import breakoutDisplay.CuttingBall;
import breakoutDisplay.breakoutPlane;
import java.awt.Container;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Edward Newkirk
 */
public class CuttingControlPanel extends javax.swing.JFrame {
    CuttingBall ball; //it is a ball
    breakoutPlane display; //where the drawing happens
    JScrollPane jsp; //so the drawing can scroll
    int i,j; // in case of for loops
    CuttingControlPanel.MouseHandler mouseHandler = new CuttingControlPanel.MouseHandler(); // for detecting clicks
    JFrame frame;
    /**
     * Creates new form CuttingControlPanel
     */
    public CuttingControlPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPanel = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        stepsAtStart = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        initialColumns = new javax.swing.JSpinner();
        initialRows = new javax.swing.JSpinner();
        StartButton = new javax.swing.JButton();
        slope = new javax.swing.JSpinner();
        start = new javax.swing.JSpinner();
        moveTypeBox = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        colorToggle = new javax.swing.JToggleButton();
        colorChooser = new javax.swing.JColorChooser();
        setClearedColor = new javax.swing.JButton();
        setPartialColor = new javax.swing.JButton();
        setLineColor = new javax.swing.JButton();
        setMarkedColor = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        intervalToMark = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        width = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        height = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hperw = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        xPrint = new javax.swing.JTextPane();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        yPrint = new javax.swing.JTextPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        hErased = new javax.swing.JTextField();
        vErased = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        revisits = new javax.swing.JTextField();
        statusDump = new javax.swing.JButton();
        totalEncounters = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        stepsPerClick = new javax.swing.JSpinner();
        moveBall = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        squareSize = new javax.swing.JSpinner();
        ResizeButton = new javax.swing.JButton();
        findBall = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        currentStage = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        steps = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setText("Initial Slope:");

        jLabel4.setText("Initial Columns:");

        jLabel3.setText("Initial Rows:");

        jLabel2.setText("Steps At Start:");

        initialColumns.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(85), Integer.valueOf(1), null, Integer.valueOf(1)));

        initialRows.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(85), Integer.valueOf(1), null, Integer.valueOf(1)));

        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        slope.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(1), null, Integer.valueOf(1)));

        start.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        moveTypeBox.setText("Each Encounter Is A Step");
        moveTypeBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveTypeBoxActionPerformed(evt);
            }
        });

        jLabel17.setText("Starting Stage:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stepsAtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(initialRows, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(initialColumns, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel17))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(slope, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(start)))
                    .addComponent(moveTypeBox)
                    .addComponent(StartButton))
                .addContainerGap(284, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(stepsAtStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(initialRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, 0)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(initialColumns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(slope, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(moveTypeBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(StartButton)
                .addGap(50, 50, 50))
        );

        TabbedPanel.addTab("Start Conditions", jPanel1);

        colorToggle.setText("Toggle Color Mode");
        colorToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorToggleActionPerformed(evt);
            }
        });

        setClearedColor.setText("Set Cleared Square Color");
        setClearedColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setClearedColorActionPerformed(evt);
            }
        });

        setPartialColor.setText("Set Partial Square Color");
        setPartialColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setPartialColorActionPerformed(evt);
            }
        });

        setLineColor.setText("Set Line Color");
        setLineColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setLineColorActionPerformed(evt);
            }
        });

        setMarkedColor.setText("Set Marked Line Color");
        setMarkedColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setMarkedColorActionPerformed(evt);
            }
        });

        jLabel19.setText("Marked Interval Size:");

        intervalToMark.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(10), Integer.valueOf(1), null, Integer.valueOf(1)));
        intervalToMark.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                intervalToMarkStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(colorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(colorToggle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setClearedColor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setPartialColor))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(setLineColor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(intervalToMark, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(setMarkedColor)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(colorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorToggle)
                    .addComponent(setClearedColor)
                    .addComponent(setPartialColor))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(setLineColor)
                    .addComponent(setMarkedColor)
                    .addComponent(jLabel19)
                    .addComponent(intervalToMark, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        colorChooser.setPreviewPanel(new JPanel());

        TabbedPanel.addTab("Colored Squares", jPanel3);

        width.setText("4");
        width.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widthActionPerformed(evt);
            }
        });

        jLabel10.setText("H/W:");

        height.setText("1");
        height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightActionPerformed(evt);
            }
        });

        jLabel8.setText("Width:");

        jLabel7.setText("Height:");

        hperw.setText("16");
        hperw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hperwActionPerformed(evt);
            }
        });

        jLabel11.setText("X:");

        xPrint.setText(".5");
        jScrollPane2.setViewportView(xPrint);

        jLabel12.setText("Y:");

        yPrint.setText(".5");
        jScrollPane3.setViewportView(yPrint);

        jLabel14.setText("Horizontal Walls Erased:");

        jLabel15.setText("Vertical Walls Erased:");

        hErased.setText("0");
        hErased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hErasedActionPerformed(evt);
            }
        });

        vErased.setText("0");
        vErased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vErasedActionPerformed(evt);
            }
        });

        jLabel16.setText("Central Square Revisited:");

        revisits.setText("0");

        statusDump.setText("Diagnostic Report");
        statusDump.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusDumpActionPerformed(evt);
            }
        });

        totalEncounters.setText("0");
        totalEncounters.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalEncountersActionPerformed(evt);
            }
        });

        jLabel13.setText("Total Encounters");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(1, 1, 1)
                                    .addComponent(jLabel8)
                                    .addGap(2, 2, 2))))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hperw, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalEncounters)
                            .addComponent(hErased)
                            .addComponent(vErased, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(revisits))
                        .addGap(18, 18, 18)
                        .addComponent(statusDump)))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(height, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(width, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(hperw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusDump)
                    .addComponent(totalEncounters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(hErased, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(vErased, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(revisits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );

        TabbedPanel.addTab("Current Statistics", jPanel2);

        jLabel1.setText("Steps Per Move:");

        stepsPerClick.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1000), Integer.valueOf(1), null, Integer.valueOf(1)));

        moveBall.setText("Move Ball");
        moveBall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBallActionPerformed(evt);
            }
        });

        jLabel5.setText("Square Size:");

        squareSize.setModel(new javax.swing.SpinnerNumberModel(2, 1, 100, 1));

        ResizeButton.setText("Resize Squares");
        ResizeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResizeButtonMouseClicked(evt);
            }
        });

        findBall.setText("Find Ball");
        findBall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findBallActionPerformed(evt);
            }
        });

        printButton.setText("Save As JPEG");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        jLabel20.setText("Current Stage:");

        currentStage.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        currentStage.setText("0");

        jLabel9.setText("Steps Taken:");

        steps.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        steps.setText("0");
        steps.setToolTipText("");
        steps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stepsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(squareSize, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(ResizeButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stepsPerClick, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(moveBall, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(findBall)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(currentStage)
                            .addComponent(printButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(111, 111, 111)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(steps, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(squareSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel1)
                    .addComponent(stepsPerClick, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResizeButton)
                    .addComponent(moveBall))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(currentStage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(findBall)
                    .addComponent(printButton)
                    .addComponent(jLabel9)
                    .addComponent(steps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void moveBallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveBallActionPerformed
        ball.tunnelFound = false;
        for (i = 0; i<Integer.parseInt(stepsPerClick.getValue().toString()); i++){
            if(!ball.tunnelFound){
                ball.move(frame);
            }
            if(i % 10000 == 9999){
                System.out.println("Steps: " + (i+1));
                //System.out.println("Height: " + ball.height() + ", Width: " + ball.width());
            } 
            if(ball.tunnelFound){
                i = Integer.parseInt(stepsPerClick.getValue().toString());
            }
        }
        updateData();
        display.repaint();
        System.out.println("Done");
        //ball.printTracker();
    }//GEN-LAST:event_moveBallActionPerformed

    private void ResizeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResizeButtonMouseClicked
        ball.resizeSquares(Integer.parseInt(squareSize.getValue().toString()));
        display.setPreferredSize(ball.gridSize());
        jsp.setPreferredSize(ball.gridSize());
        display.revalidate();
        jsp.revalidate();
    }//GEN-LAST:event_ResizeButtonMouseClicked

    private void findBallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findBallActionPerformed
        int frameWidth = frame.getWidth();
        int frameHeight = frame.getHeight();
        Double ballX = new Double(ball.getX());
        Double ballY = new Double(ball.getY());     
        Rectangle nbd = new Rectangle (ballX.intValue()-50, ballY.intValue()-50, 100, 100);
        display.scrollRectToVisible(nbd);
    }//GEN-LAST:event_findBallActionPerformed

    private void hperwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hperwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hperwActionPerformed

    private void heightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightActionPerformed

    private void widthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_widthActionPerformed

    private void intervalToMarkStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_intervalToMarkStateChanged
        display.markingInterval = Integer.parseInt(intervalToMark.getValue().toString());
        display.repaint();
    }//GEN-LAST:event_intervalToMarkStateChanged

    private void setMarkedColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setMarkedColorActionPerformed
        display.markedLineColor = colorChooser.getColor();
        display.repaint();
    }//GEN-LAST:event_setMarkedColorActionPerformed

    private void setLineColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setLineColorActionPerformed
        display.lineColor = colorChooser.getColor();
        display.repaint();
    }//GEN-LAST:event_setLineColorActionPerformed

    private void setPartialColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setPartialColorActionPerformed
        display.partialColor = colorChooser.getColor();
        display.repaint();
    }//GEN-LAST:event_setPartialColorActionPerformed

    private void setClearedColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setClearedColorActionPerformed
        display.clearedColor = colorChooser.getColor();
        display.repaint();
    }//GEN-LAST:event_setClearedColorActionPerformed

    private void colorToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorToggleActionPerformed
        display.coloredSquares = colorToggle.isSelected();
        display.repaint();
    }//GEN-LAST:event_colorToggleActionPerformed

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        // TODO add your handling code here:
        int SQUARE_SIZE = Integer.parseInt(squareSize.getValue().toString());
        int LATTICE_WIDTH = Integer.parseInt(initialColumns.getValue().toString());
        int LATTICE_HEIGHT = Integer.parseInt(initialRows.getValue().toString());
        int startingStage = Integer.parseInt(start.getValue().toString());
        int startingSlope = Integer.parseInt(slope.getValue().toString());
        boolean moveEncounter = moveTypeBox.isSelected();
        ball = new CuttingBall (startingSlope, SQUARE_SIZE, LATTICE_WIDTH,LATTICE_HEIGHT, startingStage, moveEncounter);
        frame = new JFrame("Breakout");
        if(display == null || !display.isShowing()){
            display = new breakoutPlane();
            jsp = new JScrollPane(display);
            Container c = frame.getContentPane();
            c.add(jsp);
            frame.setContentPane(jsp);
            frame.setBounds(500,0,SQUARE_SIZE*LATTICE_WIDTH + 50,SQUARE_SIZE*LATTICE_WIDTH + 50);
            frame.setSize(SQUARE_SIZE*LATTICE_WIDTH,LATTICE_HEIGHT*SQUARE_SIZE+50);
            frame.setVisible(true);
            display.addMouseListener(mouseHandler);
            display.markingInterval = Integer.parseInt(intervalToMark.getValue().toString());
        }
        display.coloredSquares = colorToggle.isSelected();
        display.setBall(ball);
        jsp.setPreferredSize(ball.gridSize());
        jsp.revalidate();
        for(i = 0; i < Integer.parseInt(stepsAtStart.getValue().toString()); i++){// start by bouncing the ball around some number of times before mouse control kicks in
            ball.move(frame);
        }
        display.repaint();
        updateData();
    }//GEN-LAST:event_StartButtonActionPerformed

    private void hErasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hErasedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hErasedActionPerformed

    private void vErasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vErasedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vErasedActionPerformed

    private void statusDumpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusDumpActionPerformed
        ball.printStatus();
    }//GEN-LAST:event_statusDumpActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        // should save a jpg with an informative title (title comes from a function on the ball)
        BufferedImage bi = new BufferedImage(ball.gridSize().width,ball.gridSize().height,BufferedImage.TYPE_INT_RGB);
        Graphics2D h = bi.createGraphics();
        display.paint(h);
        File target = new File(ball.getPrintTitle()+".png");
        try{ImageIO.write(bi,"png", target);}catch (Exception e) {}
    }//GEN-LAST:event_printButtonActionPerformed

    private void totalEncountersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalEncountersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalEncountersActionPerformed

    private void stepsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stepsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stepsActionPerformed

    private void moveTypeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveTypeBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveTypeBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CuttingControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CuttingControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CuttingControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CuttingControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CuttingControlPanel().setVisible(true);
            }
        });
    }
    
    private class MouseHandler extends MouseAdapter{ //should move the ball & repaint on releasing a click
        @Override
        public void mouseClicked(MouseEvent e) {
            if (e.getButton() == MouseEvent.BUTTON1){
                // if there's a left-click, center on the spot clicked
                int width = frame.getWidth();
                int height = frame.getHeight();
                Rectangle nbd = new Rectangle (e.getX()-width/2, e.getY()-height/2, width, height);
                display.scrollRectToVisible(nbd);
            }
            else if (e.getButton() == MouseEvent.BUTTON3){
                // if there's a right-click, center on the spot clicked and zoom by a factor of 2
                int newSize = 2*Integer.parseInt(squareSize.getValue().toString());
                squareSize.setValue(newSize);
                ball.resizeSquares(newSize);
                display.setPreferredSize(ball.gridSize());
                jsp.setPreferredSize(ball.gridSize());
                display.revalidate();
                jsp.revalidate();
                int width = frame.getWidth();
                int height = frame.getHeight();
                Rectangle nbd = new Rectangle (2*e.getX()-width/2, 2*e.getY()-height/2, width, height);
                display.scrollRectToVisible(nbd);
            }
        }
    }
    
    private void updateData(){
            // should update whatever data I'm currently chosing to display
            if(ball.latticeSizeUpdated){
                    display.setPreferredSize(ball.gridSize());
                    jsp.setPreferredSize(ball.gridSize());
                    display.revalidate();
                    jsp.revalidate();
                    ball.latticeSizeUpdated = false;
                }
            int h = ball.height();
            int w = ball.width();
            int ratio = (int) (100000.0*h/w);
            steps.setText(""+ball.stepsTaken);
            width.setText(""+w);
            height.setText(""+h);
            hperw.setText(""+ratio/100000.0);
            xPrint.setText("" + ball.normalizedX());
            yPrint.setText("" + ball.normalizedY());
            vErased.setText(""+ball.vWallsHit);
            hErased.setText(""+ball.hWallsHit);
            revisits.setText(""+ball.timesReturned);
            totalEncounters.setText("" + ball.totalEncounters);
            currentStage.setText("" + ball.currentStage);
        }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResizeButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JTabbedPane TabbedPanel;
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.JToggleButton colorToggle;
    private javax.swing.JTextField currentStage;
    private javax.swing.JButton findBall;
    private javax.swing.JTextField hErased;
    private javax.swing.JTextField height;
    private javax.swing.JTextField hperw;
    private javax.swing.JSpinner initialColumns;
    private javax.swing.JSpinner initialRows;
    private javax.swing.JSpinner intervalToMark;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton moveBall;
    private javax.swing.JCheckBox moveTypeBox;
    private javax.swing.JButton printButton;
    private javax.swing.JTextField revisits;
    private javax.swing.JButton setClearedColor;
    private javax.swing.JButton setLineColor;
    private javax.swing.JButton setMarkedColor;
    private javax.swing.JButton setPartialColor;
    private javax.swing.JSpinner slope;
    private javax.swing.JSpinner squareSize;
    private javax.swing.JSpinner start;
    private javax.swing.JButton statusDump;
    private javax.swing.JTextField steps;
    private javax.swing.JSpinner stepsAtStart;
    private javax.swing.JSpinner stepsPerClick;
    private javax.swing.JTextField totalEncounters;
    private javax.swing.JTextField vErased;
    private javax.swing.JTextField width;
    private javax.swing.JTextPane xPrint;
    private javax.swing.JTextPane yPrint;
    // End of variables declaration//GEN-END:variables
}
